repos:
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: double-quote-string-fixer

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
