[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.black]
skip-string-normalization = true
line-length = 79
exclude = '''
\(
    \.git
    oremda.egg-info
\)
'''
